{% set name = "latex-dependency-scanner" %}
{% set version = "0.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/latex-dependency-scanner-{{ version }}.tar.gz
  sha256: 2935aef14ebb3817c73a8e76f8851625e152735efba65830bb8ff3e483d005d3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - latex_dependency_scanner
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/latex-dependency-scanner/
  summary: Scan LaTeX documents for their dependencies.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/pytask-dev/latex-dependency-scanner/
  dev_url: https://github.com/pytask-dev/latex-dependency-scanner/

extra:
  recipe-maintainers:
    - tobiasraabe
