{% set name = "latex-dependency-scanner" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/latex_dependency_scanner-{{ version }}.tar.gz
  sha256: e8dcb3418bec840b31a1511f708d01484f4bbd27f49a35c4499b687f355324d1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
    - toml
  run:
    - python >=3.6

test:
  imports:
    - latex_dependency_scanner
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/latex-dependency-scanner/
  summary: Scan LaTeX documents for their dependencies.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/pytask-dev/latex-dependency-scanner/
  dev_url: https://github.com/pytask-dev/latex-dependency-scanner/

extra:
  recipe-maintainers:
    - tobiasraabe
