{% set name = "latex-dependency-scanner" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/latex_dependency_scanner-{{ version }}.tar.gz
  sha256: 35a501611602bd03c0f73e05689155b770065c1276900dc7a8b8f914a7f394ee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    - toml
  run:
    - python >=3.7

test:
  imports:
    - latex_dependency_scanner
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/latex-dependency-scanner/
  summary: Scan LaTeX documents for their dependencies.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/pytask-dev/latex-dependency-scanner/
  dev_url: https://github.com/pytask-dev/latex-dependency-scanner/

extra:
  recipe-maintainers:
    - tobiasraabe
